#   InteLib                                    http://www.intelib.org
#   The file samples/lisp/Makefile
# 
#   Copyright (c) Andrey Vikt. Stolyarov, 2000-2009
# 
# 
#   This is free software, licensed under GNU GPL v.2
#   See the file COPYING for further details.
# 
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.






clean:
	cd eratosf && $(MAKE) clean
	#cd erat_int && $(MAKE) clean
	cd permut && $(MAKE) clean
	cd perm_ufn && $(MAKE) clean
	cd isomorph && $(MAKE) clean
