#   InteLib                                    http://www.intelib.org
#   The file refal/Makefile
# 
#   Based on the file lisp/Makefile
#   Copyright (c) Vasiliy Kulikov, 2010
# 
#   Copyright (c) Andrey Vikt. Stolyarov, 2010
# 
#   This is free software, licensed under GNU LGPL v.2.1
#   See the file COPYING for further details.
# 
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.

TARGETLIBNAME = libiprolog.a

LIBSOURCES = prolog.cpp utils.cpp exceptions.cpp data.cpp engine.cpp


GENERATED_PREFIX = plgfun

MODULES = 

GENERATED_FILES = 

include ../lib.mk
