#   InteLib                                    http://www.intelib.org
#   The file samples/Makefile
# 
#   Copyright (c) Andrey Vikt. Stolyarov, 2000-2009
# 
# 
#   This is free software, licensed under GNU GPL v.2
#   See the file COPYING for further details.
# 
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.





clean:
	cd lisp && $(MAKE) clean
	cd scheme && $(MAKE) clean
	cd prolog && $(MAKE) clean
