#   InteLib                                    http://www.intelib.org
#   The file tests/prolog/Makefile
# 
#   Copyright (c) Andrey Vikt. Stolyarov, 2000-2009
# 
# 
#   This is free software, licensed under GNU GPL v.2
#   See the file COPYING for further details.
# 
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.

TESTS = t_data t_engine

LIB_OBJECTS = bin_$(TARGETDIR)/intelib/libiprolog.a \
	bin_$(TARGETDIR)/intelib/libsexpr.a

include ../common_tests.mk

