#   InteLib                                    http://www.intelib.org
#   The file tests/prolog/Makefile
#
#   Copyright (c) Ilya Strukov, 2011-2012
#
#
#   This is free software, licensed under GNU GPL v.2
#   See the file COPYING for further details.
#
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.

#TESTS = t_data t_engine t_queens t_sort t_library t_macros t_derivation
TESTS = t_data

LIB_OBJECTS = bin_$(TARGETDIR)/intelib/libiprolog.a \
	bin_$(TARGETDIR)/intelib/libsexpr.a

include ../common_tests.mk

