#   InteLib                                    http://www.intelib.org
#   The file scheme/Makefile
# 
#   Copyright (c) Vasiliy Kulikov, 2010
# 
# 
#   This is free software, licensed under GNU LGPL v.2.1
#   See the file COPYING for further details.
# 
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.

TARGETLIBNAME = libischeme.a

LIBSOURCES = $(wildcard *.cpp)

GENERATED_PREFIX = sch

MODULES = std sel str hsh io rdr m

GENERATED_FILES = $(MODULES:=.lsp)

include ../lib.mk
