// +-------------------------------------------------------------------------+
// |               I__n__t__e__L__i__b           0.6.21 development          |
// | Copyright (c) Andrey Vikt. Stolyarov <crocodil_AT_croco.net> 2000-2008. |
// |                                                                         |
// | This is free software. The library part is available under              |
// |                               GNU LESSER GENERAL PUBLIC LICENSE v.2.1.  |
// | GNU LGPL v2.1 is found in docs/gnu_gpl2.txt,  or at  http://www.gnu.org |
// |     Please see also docs/readme.txt and visit http://www.intelib.org    |
// |                                                                         |
// | !!! THERE IS NO WARRANTY OF ANY KIND, NEITHER EXPRESSED NOR IMPLIED !!! |
// +-------------------------------------------------------------------------+




/*! \file schpack.hpp
    \brief Scheme package

    See the SchExpressionPackage class description for details
 */
#ifndef INTELIB_SCHPACK_HPP_SENTRY
#define INTELIB_SCHPACK_HPP_SENTRY

#include "../sexpress/iexcept.hpp"
#include "../sexpress/sexpress.hpp"
#include "../sexpress/gensref.hpp"
#include "../tools/spkghsh.hpp"
#include "../tools/sreader.hpp"
#include "scheme.hpp"

class SchExpressionPackage;

//! Reference to a SchExpressionPackage
typedef GenericSReference<SchExpressionPackage, IntelibX_not_a_package> 
SchPackageRef;

//! The Scheme package
/*! SchExpressionPackage is used to translate strings to symbols.  
    Symbols generated by the package are stored inside the package. 
    Note there can be symbols registered but not stored in the 
    package, in which case we assume they stored somewhere else,
    e.g. defined as a named (non-dynamic) variable.
*/
class SchExpressionPackage : public SExpressionHashPackage
{
public:
        //! The type identifier
    static IntelibTypeId TypeId;

        //! The default constructor
    SchExpressionPackage();
        //! This form creates a package derived from an existing one
    SchExpressionPackage(const SchPackageRef& a_parent);

protected:
    ~SchExpressionPackage();

    // please note TextRepresentation() needn't to be reimplemented
private:
    virtual SReference CreateNewSymbolObject(const char *name) const;
};

//! A package to map the symbol QUOTE
/*! SchExpressionPackageIntelib class is intended to map the symbols
    provided by the library (presently it's only the symbol QUOTE). 
*/
class SchExpressionPackageIntelib : public SchExpressionPackage {
public:
    SchExpressionPackageIntelib();
protected:
    ~SchExpressionPackageIntelib() {}
};

#endif        // sentry
