#   InteLib                                    http://www.intelib.org
#   The file tests/sexpress/Makefile
# 
#   Copyright (c) Vasiliy Kulikov, 2010
# 
# 
#   This is free software, licensed under GNU GPL v.2
#   See the file COPYING for further details.
# 
#   THERE IS NO WARRANTY OF ANY KIND, EXPRESSED, IMPLIED OR WHATEVER!
#   Please see the file WARRANTY for the detailed explanation.


TESTS = t_sizes t_refcount t_sexpr t_ix t_leaks t_vector t_backln\
	t_wrap t_stream t_lexer t_reader t_queue t_hashtb 

LIB_OBJECTS = bin_$(TARGETDIR)/intelib/libintelibtools.a \
	bin_$(TARGETDIR)/intelib/libsexpr.a


include ../common_tests.mk

